services:
  order-postgres:
    image: postgres:18-alpine
    container_name: order-postgres
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_ROOT_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_ROOT_PASSWORD}
      ORDER_DB_USER: ${ORDER_DB_USERNAME}
      ORDER_DB_PASSWORD: ${ORDER_DB_PASSWORD}
      ORDER_DB_SCHEMA: ${ORDER_DB_SCHEMA}
    volumes:
      - ./docker-init/init-order-user.sh:/docker-entrypoint-initdb.d/init-order-user.sh
      - order_pg_data:/var/lib/postgresql
    ports:
      - "${ORDER_DB_PORT_LOCAL}:5432"

  order-service:
    build:
      context: .
    container_name: order-service
    env_file:
      - '.env'
    environment:
      SERVER_PORT: ${ORDER_SERVICE_PORT}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    depends_on:
      - order-postgres

networks:
  default:
    name: minispring-network
    external: true

volumes:
  order_pg_data: