spring:
  datasource:
    url: ${ORDER_DB_LOCAL_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${APP_JWK_SET_URI_LOCAL}
  grpc:
    client:
      channels:
        user-service-grpc:
          address: 'static://localhost:${USER_GRPC_SERVER_PORT}'
          negotiation-type: plaintext
