#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ORDER_DB_USER WITH PASSWORD '$ORDER_DB_PASSWORD';

    GRANT CONNECT, CREATE ON DATABASE $POSTGRES_DB TO $ORDER_DB_USER;

    CREATE SCHEMA IF NOT EXISTS $ORDER_DB_SCHEMA;

    GRANT USAGE, CREATE ON SCHEMA $ORDER_DB_SCHEMA TO $ORDER_DB_USER;

    ALTER USER $ORDER_DB_USER SET search_path TO $ORDER_DB_SCHEMA;

    ALTER DEFAULT PRIVILEGES IN SCHEMA $ORDER_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO $ORDER_DB_USER;

    ALTER DEFAULT PRIVILEGES IN SCHEMA $ORDER_DB_SCHEMA GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $ORDER_DB_USER;
EOSQL